### PR TITLE
Bugfixes

### PR DESCRIPTION
**Pull request by JoranHonig**
Fixed a bug in MLOAD execution, where with a symbolic index no value would be pushed.

Fixed erroneous taint analysis mutators

### CODE REVIEW

**Comment by JoranHonig** [comment]
@birdofpreyru do you know what causes this error? The tests run just fine locally

**Comment by birdofpreyru** [comment]
@JoranHonig CircleCI logs say the latest test fails cause you removed **Mythril** installation command, and some tests depend on **Mythril**; previous fail cause **Mythril** wants `laser-ethereum>=0.17.0`.
It seems that your PR is based on laser 0.16.1 - update that.

**Comment by JoranHonig** [comment]
@birdofpreyru  Oh my bad, I forgot to push the revert. This is the error I meant: https://circleci.com/gh/b-mueller/laser-ethereum/19?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by birdofpreyru** [comment]
@JoranHonig on your place, I would not change the version just by changing the version number ;) The proper would be to merge the latest `master` into your PR head, so that all updates from that version are merged into the tested code.

**Comment by JoranHonig** [comment]
So I changed the version number directly to see if it would fix the problem. 
I initially assumed that the ci would locally merge with master and do tests based on that local merged state, is it possible to do this with circle ci?

**Comment by JoranHonig** [comment]
A lot of ci systems seem to work that way (travis, vsts, teamcity have this functionality), although I might be wrong about that.
But if you don't automatically merge with upstream, whats the use of the test results? Because they won't give a good indication whether the pr will break master

**Comment by birdofpreyru** [comment]
I don't know, if code in PR passes test, and has no merge conflicts with master, why should the merge break the master? Even if it does, the merge result will be tested again anyway, and if there are some problems, it is always possible to roll back and figure out the reason.

**Pull request merged**
